<?php
//Consulta

$lang['en']['ProductID']="ProductID";
$lang['en']['BDC_MerchantSKU']="BDC_MerchantSKU";
$lang['en']['BDC_ProductCondition']="BDC_ProductCondition";
$lang['en']['BDC_ShippingStandard']="BDC_ShippingStandard Despacho";
$lang['en']['BDC_ShippingStandardlsFree']="BDC_ShippingStandardlsFree";
$lang['en']['BDC_SKU']="BDC_SKU";
$lang['en']['BuyDotComCategoryID']="BuyDotComCategoryID";
$lang['en']['BuyDotComEnabled']="BuyDotComEnabled";
$lang['en']['BuyDotComPriceUseDefault']="BuyDotComPriceUseDefault";
$lang['en']['Size']="Size";
$lang['en']['Flavor']="Flavor";
$lang['en']['Gender']="Gender";
$lang['en']['AgeSegment']="AgeSegment";
$lang['en']['PriceFallAgeGrou']="PriceFallAgeGrou";
$lang['en']['PriceFallCategory']="PriceFallCategory";
$lang['en']['PriceFallEnabled']="PriceFallEnabled";
$lang['en']['PriceFallGender']="PriceFallGender";
$lang['en']['PriceFallKeywords']="PriceFallKeywords";
$lang['en']['PriceFallPriceUseDefault']="PriceFallPriceUseDefault";
$lang['en']['PriceFallShippingType']="PriceFallShippingType";
$lang['en']['PriceFallSize']="PriceFallSize";
$lang['en']['PriceFallTitle']="PriceFallTitle";
$lang['en']['WebEnabled']="WebEnabled";
$lang['en']['MetaTitle']="MetaTitle";
$lang['en']['MetaDescription']="MetaDescription";
$lang['en']['MetaKeywords']="MetaKeywords";
$lang['en']['TopTitle']="TopTitle";
$lang['en']['PriceFallTitle']="PriceFallTitle";
$lang['en']['OverstockTitle']="OverstockTitle";
$lang['en']['AmazonTitle']="AmazonTitle";
$lang['en']['ProductName']="ProductName";
$lang['en']['Title']="Title";
$lang['en']['CustomTitle']="CustomTitle";
$lang['en']['JETCatalogType']="JETCatalogType";
$lang['en']['JETCategoryID']="JETCategoryID";
$lang['en']['JETEnabled']="JETEnabled";
$lang['en']['JETMerchantSKU']="JETMerchantSKU";
$lang['en']['JETPriceUseDefault']="JETPriceUseDefault";
$lang['en']['JETTitle']="JETTitle";
?>