<?php
//Consulta

$lang['es']['ProductID']="ProductID";
$lang['es']['BDC_MerchantSKU']="BDC_MerchantSKU";
$lang['es']['BDC_ProductCondition']="BDC_ProductCondition";
$lang['es']['BDC_ShippingStandard']="BDC_ShippingStandard Despacho";
$lang['es']['BDC_ShippingStandardlsFree']="BDC_ShippingStandardlsFree";
$lang['es']['BDC_SKU']="BDC_SKU";
$lang['es']['BuyDotComCategoryID']="BuyDotComCategoryID";
$lang['es']['BuyDotComEnabled']="BuyDotComEnabled";
$lang['es']['BuyDotComPriceUseDefault']="BuyDotComPriceUseDefault";
$lang['es']['Size']="Size";
$lang['es']['Flavor']="Flavor";
$lang['es']['Gender']="Gender";
$lang['es']['AgeSegment']="AgeSegment";
$lang['es']['PriceFallAgeGrou']="PriceFallAgeGrou";
$lang['es']['PriceFallCategory']="PriceFallCategory";
$lang['es']['PriceFallEnabled']="PriceFallEnabled";
$lang['es']['PriceFallGender']="PriceFallGender";
$lang['es']['PriceFallKeywords']="PriceFallKeywords";
$lang['es']['PriceFallPriceUseDefault']="PriceFallPriceUseDefault";
$lang['es']['PriceFallShippingType']="PriceFallShippingType";
$lang['es']['PriceFallSize']="PriceFallSize";
$lang['es']['PriceFallTitle']="PriceFallTitle";
$lang['es']['WebEnabled']="WebEnabled";
$lang['es']['MetaTitle']="MetaTitle";
$lang['es']['MetaDescription']="MetaDescription";
$lang['es']['MetaKeywords']="MetaKeywords";
$lang['es']['TopTitle']="TopTitle";
$lang['es']['PriceFallTitle']="PriceFallTitle";
$lang['es']['OverstockTitle']="OverstockTitle";
$lang['es']['AmazonTitle']="AmazonTitle";
$lang['es']['ProductName']="ProductName";
$lang['es']['Title']="Title";
$lang['es']['CustomTitle']="CustomTitle";
$lang['es']['JETCatalogType']="JETCatalogType";
$lang['es']['JETCategoryID']="JETCategoryID";
$lang['es']['JETEnabled']="JETEnabled";
$lang['es']['JETMerchantSKU']="JETMerchantSKU";
$lang['es']['JETPriceUseDefault']="JETPriceUseDefault";
$lang['es']['JETTitle']="JETTitle";
?>